### ISSUE TITLE
Installation unter Contao 4.4.12

### ISSUE THREAD

**Issue by globalindex** [TomHell/contao-social-connect-bundle#1]
Hallo,
ich habe diese Erweiterung unter Contao 4.4.12 über Contao Manager installiert. Alles soweit in Ordnung, aber ich sehe keine Optionen bei News-Archiven. Die Felder sind physisch in DB vorhanden, werden aber nicht dargestellt. Ist die letzte Version mit der Erweiterung kompatibel? Muss man was genaueres beachten?
Vielen Dank.

**Comment by globalindex** [comment]
Ich habe das schon selber gefunden.

**Comment by filipbasara** [comment]
@globalindex Wärst du so freundlich uns mitzuteilen, wie und wo du die Optionen gefunden hast? Vielen Dank!

**Comment by tefracky** [comment]
Mich würde auch einmal interessieren, wie ich das Plugin eigentlich verwende
